### ISSUE TITLE
1.16.3 NoClassDefFound ConfigLoader

### ISSUE THREAD

**Issue by BedrockLegends** [RogueLogix/BiggerSeries#11]
[crash-2020-10-13_00.13.50-fml.txt](https://github.com/RogueLogix/BiggerSeries/files/5369075/crash-2020-10-13_00.13.50-fml.txt)

**Comment by RogueLogix** [comment]
Is this repeatable?

**Comment by RogueLogix** [comment]
To answer my own question, yes.
Try downgrading to Java 8, I only test for compatibility with Java 8 and Java seems to have changed its reflection API a bit sense then.

**Comment by RogueLogix** [comment]
Works on Java 8 (discord), closing as I'm not committing to supporting newer Java versions until Mojang updates and its an issue with newer Java versions only.

**Comment by RogueLogix** [comment]
This can be fixed easily, so, it will be fixed easily.
Solutions to problems that don't even exist are great.
