### ISSUE TITLE
Can not open GUI for reactor access port

### ISSUE THREAD

**Issue by wanderingmage** [RogueLogix/BiggerSeries#20]
Can not open the access port GUI to manually insert fuel onto the reactor or change the access port input/output mode.

Forge 34.1.23
biggerreactors-1.16.3-0.1.5-beta
phosphophyllite-1.16.3-0.0.2-beta

![2020-10-18_13 08 52](https://user-images.githubusercontent.com/26194881/96376209-2bc8e800-1143-11eb-85fc-0a8836fb7d00.png)

No Crash report. Just a functionality problem.

**Comment by RogueLogix** [comment]
#13, use a hopper and a smart wrench or configurator, it will also push out an input if no output exist
