### ISSUE TITLE
chunkCachedBlockStateIteration NPE

### ISSUE THREAD

**Issue by phit** [RogueLogix/BiggerSeries#23]
Started happening randomly and gave us a hard crashloop, not sure what's actually null I just threw it in a try/catch for now. That seems to have solved the crashloop for now.

Log: https://gist.github.com/phit/6302064aba4001ce091ed2db0a592943
`phosphophyllite-1.16.3-0.0.4-beta`
`biggerreactors-1.16.3-0.1.9-beta`
Running All The Mods 6

Note this also happened with `phosphophyllite-1.16.3-0.0.2-beta` and `biggerreactors-1.16.3-0.1.5-beta` I had hoped updating would fix it, it did not.

Thanks for looking into this!

**Comment by phit** [comment]
Talked to the user that caused it, they are building a max size reactor and placed a block on top of the structure like this on accident. Just managed to reproduce it, when they place a block like this I can see the try/catch logging the NPE in the console.

![image](https://user-images.githubusercontent.com/2097483/97057771-46102500-158c-11eb-984c-f52463f08d74.png)

**Comment by RogueLogix** [comment]
It's a null chunk section, does this happen to be a large non-chunk aligned reactor with a lot of air space in it?

**Comment by phit** [comment]
"yes" he said

![image](https://user-images.githubusercontent.com/2097483/97058019-ed8d5780-158c-11eb-87aa-a1ae5b9a8e7c.png)

**Comment by RogueLogix** [comment]
yup, that has the alignment that i can see causing this

if you could grab the phosphophyllite jar (in the zip file) in the below CI build and replace the server side jar (client side is fine) and verify that its fixed, that would be great

[https://github.com/RogueLogix/BiggerSeries/actions/runs/325032351](https://github.com/RogueLogix/BiggerSeries/actions/runs/325032351)

seems you are running an ATM6 server, this will be in the next ATM update (current is 1.1.8, so 1.1.8b or 1.1.9)

**Comment by phit** [comment]
just got in bed, I'll throw it on the server in the morning and let you know then, thanks for the quick reply

**Comment by phit** [comment]
no crashes in the past 5 hours, seems to have fixed it, thanks!
