### ISSUE TITLE
Cave Air is an invalid Reactor Component

### ISSUE THREAD

**Issue by phit** [RogueLogix/BiggerSeries#24]
just reported by a player

![image](https://user-images.githubusercontent.com/2097483/97059577-131c6000-1591-11eb-8234-15dc7cbf0ca3.png)

would be nice if you could also add `minecraft:cave_air`, yes vanilla has two types of air.. yes its dumb
https://github.com/RogueLogix/BiggerSeries/blob/3076f5eb1f8c49f12e14226758073271cb2a8b38/BiggerReactors/src/main/java/net/roguelogix/biggerreactors/Config.java#L207

**Comment by RogueLogix** [comment]
to fix now, you can duplicate the air entry in the config and change the one from air to cave_air, and it will work, ill add it to default config though

**Comment by RogueLogix** [comment]
added to default config with the same values as air
