### ISSUE TITLE
JEI Icons missing for both Bigger Reactor & Phosphophyllite

### ISSUE THREAD

**Issue by ClaudiusMinimus** [RogueLogix/BiggerSeries#27]
Many icons are missing for both Bigger Reactor & Phosphophyllite as shown in the screenshot below. Thank you, CM

Minecraft: 1.16.63
Forge: 34.1.25
biggerreactors-1.16.3-0.2.0-beta
phosphophyllite-1.16.3-0.0.5-beta

![2020-10-29_19 50 08](https://user-images.githubusercontent.com/17887664/97651003-a4bc1f80-1a20-11eb-884c-de00ae4e74ae.png)

**Comment by RogueLogix** [comment]
Black hole and White hole models were added in Phos 0.1.1

**Comment by RogueLogix** [comment]
only icons that are missing now should be the bucket ones, which is why #25 is open, so, im gonna close this
