### ISSUE TITLE
Reactor Access Port

### ISSUE THREAD

**Issue by ghost** [RogueLogix/BiggerSeries#30]
I built my reactor and got it operational but a few things are stopping me from using it. The access port wont open the gui and it says its full of Cyanite Ingots even though I haven't turned the reactor on.

**Comment by RogueLogix** [comment]
What version are you on? The port showing full of Cyanite to inventory accessors is expected behaviour as it always reports that regardless of reactor state, what are you doing such that you see this?

**Comment by ghost** [comment]
Im on 1.16.3 with the pack All The Mods 6 and crouching shows its full

**Comment by RogueLogix** [comment]
_Did not know that crouching would show that._

What ATM6 version are you on? Almost every one updates BiR.

**Comment by RogueLogix** [comment]
Going to close this as i haven't heard back from you in a week, if you cant open the GUI, ensure you are on the latest version, older versions didn't have it yet.
