### ISSUE TITLE
Turbine causing server crash

### ISSUE THREAD

**Issue by Nagispace** [RogueLogix/BiggerSeries#31]
I updated the mod from `biggerreactors-1.16.3-0.1.7-beta.jar` to `biggerreactors-1.16.3-0.2.2-beta.jar` on a server.
Breaking turbine blocks (frames, glass, controller, etc...) doesn't drop them (this isn't a server lag I can break other blocks just fine)
Trying to replace the blocks you broke with turbine blocks will crash the server but placing other random blocks will not.

### edit

The crash log :

[crashlog.txt](https://github.com/RogueLogix/BiggerSeries/files/5514083/crashlog.txt)

**Comment by RogueLogix** [comment]
crash already fixed with 0.2.3, loot tables should be fine, if the lack of drops continues, then its a problem
