### ISSUE TITLE
Server Crash when player logs in

### ISSUE THREAD

**Issue by ftog-thorgal** [RogueLogix/BiggerSeries#34]
Modpack: ATM6 version 1.2.1

biggerreactors-1.16.3-0.2.2-beta.jar
phosphophyllite-1.16.3-0.1.1-beta.jar

Server crashes as soon as any player gets near a certain players base.

Crash report: https://gist.github.com/ftog-thorgal/9b86be8df83f9ad1c70c402e52fdad37

**Comment by RogueLogix** [comment]
already fixed in commit b2f52ae45c59408f2ca5a1166000267af5ec7bdb Phosphophyllite-0.2.0
