### ISSUE TITLE
Reactor just randomly wont work after short bit of being built

### ISSUE THREAD

**Issue by camcamhow** [RogueLogix/BiggerSeries#35]
Reactor just randomly wont work has everything it needs will work for a short bit after being built then dies and wont run 
not sure how this is happening probably a conflict with one of the other mods 
Minecraft Version: 1.15.2

these are the mods i am using
[1.15.2] BobLib v0.1.9.jar
[1.15.2] SecurityCraft v1.8.20.2.jar
[1.15.2] Simple Homes v1.0.8.jar
acceleratorcraft-1.2.jar
angelring-1.15.2-1.2.0.jar
AppleSkin-mc1.15.2-forge-1.0.14.jar
appliedenergistics2-7.0.5.jar
AutoRestart-1.15.2-1.1.0.jar
BackTools-1.15.2-8.0.0.jar
betteranimalsplus-1.15.2-10.0.0.jar
biggerreactors-1.15.2-0.0.2-beta.jar
BiomesOPlenty-1.15.2-10.0.0.366-universal.jar
Blur-1.1.0-1.jar
BonsaiTrees-2.1.2.6.jar
Bookshelf-1.15.2-5.6.40.jar
Botania-r1.15-388.jar
buildinggadgets-3.4.1.jar
Chargers-1.15.2-2.0.0.1.jar
ChickenChunks-1.15.2-2.5.1.79-universal.jar
ClickMachine-1.15.2-3.0.2.jar
Clumps-5.0.2.6.jar
CobbleForDays-1.1.3.jar
CodeChickenLib-1.15.2-3.3.2.383-universal.jar
cofh_core-1.15.2-1.0.2.jar
config-2-3.0.jar
CosmeticArmorReworked-1.15.2-v3a.jar
CraftingCraft_1.15.2-8.0.1.jar
craftingstation-3.1.0.jar
CraftingTweaks_1.15.2-11.0.1.jar
CraftTweaker-1.15.2-6.0.0.24.jar
create-mc1.15.2_v0.2.4e.jar
Cucumber-1.15.2-3.0.9.jar
curios-FORGE-1.15.2-2.0.2.6.jar
Cyclic-1.15.2-0.7.0.jar
Decoration and furniture mod.jar
drawbridges-1.15.2.jar
DrawersTooltip-1.15.2-1.1.0.jar
Druidcraft-1.15-0.4.45.jar
elevatorid-1.15.2-1.7.1.jar
EnchantmentDescriptions-1.15.2-2.0.9.jar
EquipmentTooltips-1.15.2-1.4.3+14.jar
ExtendedCrafting-1.15.2-2.0.6.jar
ExtraButtons-1.15.2-3.0.0.jar
extratags-1.1.jar
FarmersDelight-1.15.2-0.2.3.jar
FarmingForBlockheads_1.15.2-6.1.5.jar
FastLeafDecay-v22.1.jar
FluxNetworks-1.15.2-5.0.3-4.jar
ftb-backups-2.1.0.2.jar
furniture-7.0.0-pre16-1.15.1.jar
Gobber2-1.15.2-2.2.103.jar
gravestone-1.17.5.jar
iChunUtil-1.15.2-8.0.3.jar
IKnowWhatImDoing-3.1.0-forge.jar
ImmersiveEngineering-1.15.2-4.1.1-125.jar
Industrial Agriculture[Core]-1.15.2-1.7.0.jar
Industrial Agriculture[Gobber]-1.15.2-1.6.0.jar
industrial-foregoing-1.15.2-2.3.3-e356e61.jar
inventorygenerators-1.15.2-1.0.0.jar
inventorysorter-1.15.2-17.0.0.jar
invtweaks-1.15.2-2.0.9.jar
ironchest-1.15.2-10.0.3.jar
jei-1.15.2-6.0.3.15.jar
jeiintegration_1.15.2-3.1.1.2.jar
JEITweaker-1.15.2-1.0.1.3.jar
journeymap-1.15.2-5.7.0b3.jar
jumbofurnace-1.15.2-1.0.0.2.jar
JustEnoughResources-1.15.2-0.10.1.77.jar
libnonymous-1.15.2-1.1.1.5.jar
light-overlay-4.7.2.jar
Ma-Essentials-1.15.2-3.1.1.jar
mcjtylib-1.15-4.1.12.jar
mcw-bridges-1.0.4fix-mc1.15.2.jar
mcw-doors-1.0.1fix-mc1.15.1-2.jar
mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar
mcws-roofs-1.15.2-v2.0.0.jar
mcws-win-1.15.2-v1.0.2.jar
mcw-trapdors-1.0.0fix-mc1.15.2.jar
Mekanism-1.15.2-9.10.9.422.jar
MekanismGenerators-1.15.2-9.10.9.422.jar
minecolonies-0.13.443-BETA-universal.jar
MixinBootstrap-1.0.5.jar
mobcatcher-2.2.jar
modular-routers-1.15.2-6.1.3-32.jar
morered-1.15.2-1.0.1.0.jar
Morpheus-1.15.2-4.2.50.jar
MouseTweaks-2.13-mc1.15.1.jar
MysticalAgradditions-1.15.2-3.0.1.jar
MysticalAgriculture-1.15.2-3.0.10.jar
MysticalCustomization-1.15.2-1.0.0.jar
Neat 1.6-22.jar
noautojump-1.15.2-1.jar
OreExcavation-1.7.151.jar
pamhc2crops-1.15.2-1.0.5.jar
Passive Pets (1.2.1) for 1.15.2.jar
Patchouli-1.15.2-1.2-35.jar
Placebo-1.15.2-3.1.0.jar
prefab-1.5.0.9.jar
QuantumStorage-1.15.2-5.1.1.jar
reap-1.12.4.jar
ReAuth-1.14-1.15-3.8.1.jar
refinedstorage-1.8.8.jar
rftoolsbase-1.15-1.1.8.jar
rftoolsbuilder-1.15-2.1.13.jar
rftoolspower-1.15-2.2.6.jar
rftoolsstorage-1.15-1.1.11.jar
rftoolsutility-1.15-2.1.17.jar
rsgauges-1.15.2-1.2.4.jar
ServerTabInfo-1.15.2-1.2.8.jar
SilentGear-1.15.2-1.11.3+160.jar
SilentLib-1.15.2-4.6.6+59.jar
SimpleDiscordRichPresence-1.15.2-1.2.7.jar
simplefarming-1.15.2-1.3.4.jar
SimpleStorageNetwork-1.15.2-1.0.1.jar
simplybackpacks-1.15.2-1.4.11.jar
SimplyJetpacks2-1.15.2-2.5.3.4.jar
SolarFluxReborn-1.15.2-15.2.3.jar
solcarrot-1.15.2-1.9.7.jar
speedyhoppers-1.15.2-2.jar
StorageDrawers-1.15.2-7.0.3.jar
structurize-0.13.94-ALPHA-universal.jar
theoneprobe-1.15-2.0.7.jar
thermal_expansion-1.15.2-1.0.2.jar
thermal-1.15.2-1.0.2.jar
thutcore-1.15.2-7.2.1.jar
thuttech-1.15.2-8.2.2.jar
tinyprogressions-1.15.2-4.0.8.jar
titanium-1.15.2-2.4.2.jar
torchmaster-2.2.2.jar
Trading_Players_1.1.jar
trash-1.15.2-0.2.0.jar
TrashSlot_1.15.2-11.0.0.jar
VivecraftForgeExtensions-1.15.2-1.3.1.jar
Waddles-1.15.2-0.8.6.jar
Waystones_1.15.2-6.0.2.jar
woot-1.15.2-1.1.1.2.jar
worldedit-forge-mc1.15.2-7.1.0.jar

**Comment by RogueLogix** [comment]
1.15.2 is no longer supported
