### ISSUE TITLE
computercraft programs not working

### ISSUE THREAD

**Issue by foxdarts** [RogueLogix/BiggerSeries#37]
hello so i have tried to run multiple computercraft programs on a bigger reactor reactor and turbine and i cant seem to get computercraft to recognize the reactors at all.

**Comment by RogueLogix** [comment]
the computercraft peripheral name changed from BigReactors-reactor and BigReactors-turbine to bigger-reactor and bigger-turbine respectively.

**Comment by foxdarts** [comment]
ok i changed those now when i try to run i get no such method getNumberOfBlades.

**Comment by RogueLogix** [comment]
seems i missed some functions when i ported over the CC functionality
