### ISSUE TITLE
Cyanite Reprocessor Feature Enhancement Idea

### ISSUE THREAD

**Issue by papaworld** [RogueLogix/BiggerSeries#40]
Hi... really like the BR series since 1.7.10. Thank you for porting it up to current. BTW: even tho "over your head", you're doing well and keep up the good work. It is well appreciated!

The proper feeding of Blutonium and Yellorium/Uranium fuel to the reactor was real easy in 1.7.10 using a TE retriever. In 1.16.x with the available item handling mods don't make it so easy and dependable... I've tried lots of ways and got it to work 100% using extra controls feeding the fuel properly using two methods, but it's a bunch of extra stuff that clutters a clean looking install.

Idea: is it possible to add a 3rd inventory slot in the Reprocessor for Yellorium/Uranium and the Reprocessor would pull the Blutonium FIRST if available, then if not available, would pull the Yellorium/Uranium SECOND? And, the Cyanite item input would also allow Yellorium/Uranium fuel on the same item input connection both going to their proper slot (cyanite slot0 and yellorium/uranium slot2)?

ThanX for your consideration.

**Comment by gizmocodes** [comment]
Hey, we dig the idea, though we're not sure if we want to put that functionality inside the Reprocessor itself. What we might do is add a fuel buffer that can be used in conjunction with the Reprocessor, which would prioritize Blutonium over Yellorium/Uranium (depending on how configured), which would make it Reactor -> Reprocessor -> Fuel Buffer -> Reactor. Will respond later if/when we make a decision. Thanks for the suggestion!

**Comment by papaworld** [comment]
Yeah, prioritizing the fuel input access port is a super idea. Keeping in mind that both the blutonium from the reprocessor and yellorium/uranium from storage would both have "push" mode enabled on the item transport pipe.

**Comment by RogueLogix** [comment]
I am going to reject this suggestion as its out of the scope of the mod. Existing item handling mods not being able to do the things you want how they want isn't reason enough for me to add something like this to the mod. While it may not be the cleanest, you can have this reliably automated in numerous ways in 1.16 as is.
