### ISSUE TITLE
Bigger Reactors Moderators

### ISSUE THREAD

**Issue by papaworld** [RogueLogix/BiggerSeries#42]
Hi,  been playing 1.16.3 and created my own liquid moderators list in the JSON5 file. Now, playing 1.16.4 v0.3.0-beta... the Moderator parms/function is not showing up in the new JSON5 file. Is there a way to add custom user Moderators or reactivate this function? I noticed the update stated "Moderator Datapacks" (yuck)... how do I do it?

The only reason I don't like datapacks 'cause it is per world... not global to the instance being played.

ThanX

**Comment by RogueLogix** [comment]
yea, moderators are now registered via the datapack. while not as easy for a user to edit, it is significantly easier for me to manage them and for other mods to integrate. moderators json/josn5 files are searched for in biggerreactors:ebcr/modertors in the datapack loaded at world load, you can look at the ones here for examples of what they look like. i added a few new moderators in this update, if you have other suggestions feel free to PR it to just tell us on discord

**Comment by papaworld** [comment]
MC 1.16.4
FML 35.1.12 and 35.1.13
BR 0.3.0 beta
Phos 0.3.2 beta

The only mods loaded are BR and Phos, the datapack on world create/load did not generate. Here's what happened on another World creation...
![BRdatapackerror](https://user-images.githubusercontent.com/50890375/102435502-5963cd80-3fdc-11eb-9ed2-066eae11516c.png)

**Comment by RogueLogix** [comment]
that doesnt tell me anything

**Comment by papaworld** [comment]
Highlighting each datapack states: "mod is for an older version of minecraft". BR works in the world... but, does not generate datapack data.

**Comment by papaworld** [comment]
MC 1.16.4
FML 35.1 29
BR 1.16.4-0.4.3-beta
Phos 1.16.4-0.4.0-beta

History: added my own liquid moderators to 1.16.3 version... worked great.

With 1.16.4, I can not locate "biggerreactors:ebcr/modertors" datapack you mentioned will be generated on World load so I can add liquid moderators. Can you tell me where it is or an example of where and how it can be created?

I use the standard MineCraft Launcher. MineCraft is installed on drive C.
My 1.16.4 instance is located at "F:\MCv16_4". Did a manual search and windows auto search with no hidden/show system... did not find anything. Please help me out. Tx

**Comment by RogueLogix** [comment]
you would need to use a custom datapack, and put stuff in the directory that corresponds to the `biggerreactors:ebcr/moderators` resource location. you can achieve this in a multitude of ways including but not limited to creating a mod of your own, or using a custom datapack loader mod such as `Global Data- & Resourcepacks` or `Open Loader`

**Comment by papaworld** [comment]
OK, thank you.
