### ISSUE TITLE
[BiR 0.3.0] Manual Eject Button in Access Port Doesn't Work

### ISSUE THREAD

**Issue by gizmocodes** [RogueLogix/BiggerSeries#43]
If you've found this bug report through Curse or Google, we've already realized it too. Basically, the Manual Eject Button in the Reactor Access Port sends an `ejectWaste` request to its corresponding tile. However, the tile is missing a request handler for that, so no action occurs. A fix should be out soon. For now, try and use the Auto-eject Toggle in the Reactor Terminal, as that should still work as intended (though if that somehow broke too, please do tell).

**Comment by RogueLogix** [comment]
1e9c2a7dda46a0ebe6af7bb5b8905143a06b6076
