### ISSUE TITLE
Input/output UI does not display properly

### ISSUE THREAD

**Issue by SheaMCl** [RogueLogix/BiggerSeries#47]
I'm not sure if this is a bug or a personal issue, but I can't seem to put fuel into or take waste out of the reactor. The only menu that appears is one that allows me to switch the usage of the port (i.e. import or export). I've tried to find out for myself if this was an issue or not, but it seems like nobody is having the same issues.

**Comment by RogueLogix** [comment]
that is correct behavior, you are supposed to use a hopper/pip to insert fuel, and have it eject to a chest or be pulled out with a pipe

**Comment by SheaMCl** [comment]
Thanks, I appreciate it
