### ISSUE TITLE
Config File is a .json5 File

### ISSUE THREAD

**Issue by Mikaaah** [RogueLogix/BiggerSeries#48]
The config file is currently listed as a .json5 file. I doubt this would be intended, as now its not actually a proper file.
![dc9ad136264634cf35929134cd6dbe57](https://user-images.githubusercontent.com/59295501/103431952-a3ea6a00-4bd8-11eb-863b-ca83796f30bf.png)

**Comment by gizmocodes** [comment]
This is intentional. JSON5 is an extension of the JSON standard, and is is
the format we use for BiR and Phosphophyllite.

**Comment by RogueLogix** [comment]
TOML support will be added, currently its json5
