### ISSUE TITLE
UI display incorrect RF storage

### ISSUE THREAD

**Issue by jmac460** [RogueLogix/BiggerSeries#49]
Hello, not sure exactly what is causing the issue, but at some point the UI stopped functioning with the RF storage meter and quickly flips between 1.0/0.0 constantly. Also, something is occurring along with that which is deleting all the fuel in the reactor and deleting the waste. I filled a (ID) 3x3x3 reactor to the brim (with 4 columns) which equated to about 48 ingots of fuel. I let it run, but about halfway through its life it just deleted all the fuel.

**Comment by RogueLogix** [comment]
what version?

**Comment by jmac460** [comment]
Ah, sorry, it was version 0.4.1

**Comment by RogueLogix** [comment]
can you show what exactly what the UI is doing, and exact steps to cause the fuel to be deleted.

**Comment by jmac460** [comment]
I am not sure how to repeat it, seems random. I will try my best to see, though. (It seems as if the only common thing that happens is a server restart.... but I can't be too sure)

**Comment by RogueLogix** [comment]
im going to close this issue as it has been sitting for over two week
