### ISSUE TITLE
Fuel Usage and Reactivty Rate become NaN

### ISSUE THREAD

**Issue by j-mie** [RogueLogix/BiggerSeries#50]
![image](https://user-images.githubusercontent.com/1857320/103469637-4c2a3b00-4d5f-11eb-9bf0-003c8d853244.png)
![image](https://user-images.githubusercontent.com/1857320/103469639-52b8b280-4d5f-11eb-8e25-2414279e5d17.png)

23x23x1 internal reactor size with graphite blocks in the middle.

**Comment by RogueLogix** [comment]
what version, and any modified config options?

**Comment by j-mie** [comment]
biggerreactors-1.16.4-0.3.0-beta - from All The Mods 6, I think it's the default config but it's here: https://github.com/AllTheMods/ATM-6/blob/master/config/biggerreactors-common.json5

We think it might have happened when we put a weird value into the reactor via `setAllControlRodLevels`

**Comment by RogueLogix** [comment]
what value did you put in? because that could easily cause it

**Comment by RogueLogix** [comment]
could reproduce and fix the fuel consumption, couldn't reproduce the reactivity yet.

you can reset your control rods by given setAllControlRodLevels a valid value, and it should work fine

**Comment by RogueLogix** [comment]
figured out the reactivity one, race condition there, to fix it, place a block one away from the reactor, place a block that fills the gap, then break them, that will reset your reactor's internal simulation and reset the fertility to a valid number. do this along with resetting the control rods to a non-nan value, and you should be all good

**Comment by j-mie** [comment]
thank you!

**Comment by Possibly-Pos** [comment]
I just want to try to simplify what you said @RogueLogix 

Break any control rod and replace with a casing, break the casing and place the control rod back. This resets the internals. 

This is how I understood it and it did fix the problem for me.
