### ISSUE TITLE
cyanite won't leave reactor through access ports (1.15.2)

### ISSUE THREAD

**Issue by grandogarndo** [RogueLogix/BiggerSeries#51]
maybe it is because I'm playing in 1.15.2, but the one probe says that there are 64 ingots in the reactor, but nothing comes out no matter what pipe I put there. I feel like I'm missing something.
https://drive.google.com/file/d/1Dryr4nvjz46MZ9HqHu4uCa_8x4Sb8EuY/view?usp=sharing

**Comment by gizmocodes** [comment]
1.15.2 is no longer supported, and issues with it will not be fixed (unless absolutely necessary). However, in your video, the access port is yellow, as in set to input. You must use a reactor wrench to set it to output, which should invert the arrows and change its colors.

**Comment by RogueLogix** [comment]
Besides the 1.15.2 version not being supported anymore, that 64 cyanite is hard coded in, and is only there to get some pipes to function correctly. You wont be able to remove anything that isn't actually in the reactor. Newer 1.16.3/4 versions report the number of ingots the reactor has accurately sense #30.

https://github.com/RogueLogix/BiggerSeries/blob/1.15/src/main/java/net/roguelogix/biggerreactors/classic/reactor/tiles/ReactorAccessPortTile.java#L99
