### ISSUE TITLE
Combine the Mod DataPack with User JSON5

### ISSUE THREAD

**Issue by papaworld** [RogueLogix/BiggerSeries#52]
Guess the title says it. Allow mod users to place moderator/coil options of their choosing in the original JSON5 which would be loaded with the DataPack and combined. Easier for the user and easier integration of other mods by BG. Just saying.

**Comment by RogueLogix** [comment]
I removed the config option as it isn't the best option for mod or modpack authors to use. The datapack method i use currently allows for extremely easy integration by mod and modpack authors. It is a little more tedious for end users to edit their moderators/coils, but that is on purpose, as the balance of these things isn't something that should be messed with in most cases, even by modpack authors. I already explained to you how to add your own in #42, so, for anyone googling this and wondering how, its in that issue
