### ISSUE TITLE
error loading mod

### ISSUE THREAD

**Issue by Komatbed** [RogueLogix/BiggerSeries#55]
Mod File: biggerreactors-1.16.4-0.4.3-beta.jar
	Failure message: Bigger Reactors (biggerreactors) has failed to load correctly
		java.lang.NoClassDefFoundError: mezz/jei/api/recipe/category/IRecipeCategory
[crash-2021-01-08_19.33.40-fml.txt](https://github.com/RogueLogix/BiggerSeries/files/5788857/crash-2021-01-08_19.33.40-fml.txt)

**Comment by jeremiahwinsley** [comment]
0.4.3 has an unintentional dependency on JEI, which is fixed in #54. That should be in the next release, or you can add JEI.
