### ISSUE TITLE
What do the moderation terms mean

### ISSUE THREAD

**Issue by FallenRecruit** [RogueLogix/BiggerSeries#56]
I was looking at the wiki (https://biggerseries.net/wiki/Main_Page) trying to work out how to make my reactor better and I read the words Absorption, Efficiency, Moderation and Conductivity, this made me question what each of these terms meant and how I can best utilize this table, So to get to my question, In simple terms what do each of these 4 values do?

**Comment by RogueLogix** [comment]
wiki has been updated with an explanation on how these terms are used

**Comment by FallenRecruit** [comment]
Cheers, looks good now
