### ISSUE TITLE
Reactor randomly breaks after building.

### ISSUE THREAD

**Issue by Mrdgers** [RogueLogix/BiggerSeries#58]
I am playing all the mods 6 v1.4.1 with bigger reactors 0.4.3-betajar. I have been running into an issue where I build my 7x7 reactor and it works for a time but then it breaks. the multiblock deforms and wont rebuild in the same spot I have to move entirely new spot (appears to be I cant have ANY blocks of the rebuild in the same space as the old reactor). I am also reporting on the ATM side just incase its some conflict. Let me know if an update will fix this (server doesn't update often but it can be done. )

![2021-04-03_14 59 43](https://user-images.githubusercontent.com/78296397/113490449-8d7dd400-948f-11eb-8cc1-bc11e59c7e1e.png)
![2021-04-03_14 59 52](https://user-images.githubusercontent.com/78296397/113490455-9373b500-948f-11eb-869c-a4ba41f4846d.png)

**Comment by RogueLogix** [comment]
There were some fixes made in newer phosphophyllite versions that may fix this, please update to the latest version and see if that fixes the issue

**Comment by RogueLogix** [comment]
im going to close this as its been dead for nearly two weeks
