### ISSUE TITLE
All The Mods 6 Crash

### ISSUE THREAD

**Issue by FlamenWolf** [RogueLogix/BiggerSeries#59]
For some reason, in the All the Mods 6 modpack, bigger reactors has been causing the game to crash for me. I need to remove the mod to even be able to open the game.

Here is the crash report:
[crash-2021-04-04_16.09.40-fml.txt](https://github.com/BiggerSeries/BiggerSeries/files/6255609/crash-2021-04-04_16.09.40-fml.txt)

**Comment by RogueLogix** [comment]
https://github.com/BiggerSeries/BiggerReactors/issues/7
