### ISSUE TITLE
Client crash loop after placing reactor port on TNP Limitless 4 1.17

### ISSUE THREAD

**Issue by ShadowMagnus** [RogueLogix/BiggerSeries#62]
Modpack: TNP Limitless 4
Bigger Reactor mod version: 1.17.1-0.6.0-alpha.2

Issue:
Client goes into crash loop after attempting to place a reactor port on the multi block structure 5x4x5.

**Comment by RogueLogix** [comment]
log?

**Comment by ShadowMagnus** [comment]
my apologies, forgot to add b4 going to sleep. Here is the log. 
[crash-2021-08-27_21.08.51-client.txt](https://github.com/BiggerSeries/BiggerSeries/files/7070774/crash-2021-08-27_21.08.51-client.txt)
