### ISSUE TITLE
Reactant Coolant Port doesn't input water

### ISSUE THREAD

**Issue by ghost** [RogueLogix/BiggerSeries#63]
I'm fairly new to this mod so this might be a mistake on my side. The problem is whenever I put a water pipe into the reactant coolant port (input), the reactor terminal's ui doesn't show any water being inputted. 
![Base Profile Screenshot 2021 12 19 - 12 10 18 63](https://user-images.githubusercontent.com/96308952/146687621-210df72a-15d3-4160-a03e-d80153289a23.png)

**Comment by RogueLogix** [comment]
what pipes are you using?

**Comment by ghost** [comment]
some mod called "Pipez", other mod alternatives don't seem to be up to date.

**Comment by RogueLogix** [comment]
Pipez does work in 1.18.1
![image](https://user-images.githubusercontent.com/9971693/146691408-35cfcd3d-1218-4a23-9148-907a073f1096.png)

**Comment by RogueLogix** [comment]
Closing due to no response. If you can reliably reproduce with known working mod, please open a new issue
