### ISSUE TITLE
Unknown multiblock error

### ISSUE THREAD

**Issue by WhatAVI** [RogueLogix/BiggerSeries#64]
I was trying out some structures in singleplayer (a 9x9x9 reactor) and I had an error come up in chat, I'm not too sure what happened as I've been able to make 3x3x3 ones work -
![2021-12-23_11 53 20](https://user-images.githubusercontent.com/35369664/147236903-2c5961b5-a774-4749-a608-59f8986d5e22.png)

I should note that I'm on the 1.18.1 version, and fairly new so it might be a problem on my end

**Comment by SereneSadie** [comment]
Been having issues with my setups in ATM 7 for 1.18.1 as well. What I found is that picking up and replacing the terminal would give errors about the minimum size each time, and the listed dimensions would change if breaking and replacing other blocks in the reactor frame.

A full world reload eventually made the reactor form properly as originally intended, so I suspect block updates aren't being applied properly when it scans for multiblock.

**Comment by RogueLogix** [comment]
ensure you are on the latest update of BiR/Phos, an issue very similar to this was fixed in alpha.9
the latest ATM 7 has this update
