### ISSUE TITLE
Reactor stops working when...

### ISSUE THREAD

**Issue by Berridex** [RogueLogix/BiggerSeries#67]
Reactor stops working when I travel to different dimensions (Nether, End, Blue Skies etc...). I have to build the reactor's smallest version, which then resets it and I can rebuild my bigger version. Also, once I get the reactor working again, when I end the session and log back in, say the next day, the reactor is again not working and I have to go through the entire process of building the smallest version of a reactor possible, which resets it and then I can build the bigger version. I don't think there are any photos I can upload to help show this.

**Comment by RogueLogix** [comment]
Without version info, I cant debug this. Assuming 1.18.1, Phosphophyllite-0.6.0-beta.0.3 may fix it.

**Comment by Berridex** [comment]
My apologies. The version is 1.16.5.

**Comment by RogueLogix** [comment]
there are a lot of fixes in 1.17/1.18 that haven't been backported to 1.16.5 yet, your issue will probably be solved by one of them, if its persists with Phosphophyllite 0.5.2 (whenever i get around to making that) open a new one.

**Comment by Berridex** [comment]
Cool. Thank you
