### ISSUE TITLE
Power not universal

### ISSUE THREAD

**Issue by SquidNeko** [RogueLogix/BiggerSeries#68]
With previous iterations of this mod, the reactor used to be universal with its power and able to power any machine mod and output the right type itself.

However just found out it outputs MFE and will not accept cables that uses IE.
Unlike older Iterations where that worked fine.

**Comment by RogueLogix** [comment]
Previous iterations have supported RF, Tesla, and FE. BiR supports the only one of those that still exists, which is FE.
RF (BR 1.5.2-1.7.10, ER 1.9.4-1.11.2)
Tesla (ER 1.9.4-1.12.2)
FE (ER 1.12.2)
