### ISSUE TITLE
https://biggerseries.net/ is down

### ISSUE THREAD

**Issue by Eastborn** [RogueLogix/BiggerSeries#70]
as said in the title, the website for biggerseries is not reachable

i do get a reply by pinging 45.12.110.xxx

**Comment by RogueLogix** [comment]
On purpose, I'm doing server (well VM and network) maintenance/reconfiguration that I've been putting of for months now, ill leave this open until I'm done with that though

**Comment by EzequielDM** [comment]
Any ETA as to when the website is coming back up? Really miss a wiki
