### ISSUE TITLE
All the mods 6 bigger reactors TOML crash

### ISSUE THREAD

**Issue by TheKraken1134** [RogueLogix/BiggerSeries#73]
Everytime I load up all the mods 6 my bigger reactors mod fails to load because of incompatible TOML and I'm lost because I have no idea how to fix it at this point
[crash-2022-11-07_23.19.28-fml.txt](https://github.com/BiggerSeries/BiggerSeries/files/9957599/crash-2022-11-07_23.19.28-fml.txt)
here is my crash report

**Comment by Shawi7** [comment]
Same Issue ,
I tried almost every thing but same Issue keep happening .

**Comment by RogueLogix** [comment]
Don't change the config file extension, it isn't a TOML file. As the error says TOML isn't supported in 1.16 and you must use JSON5, which the config was generated as. TOML support was added to the config system in 1.17.1.

**Comment by TheKraken1134** [comment]
how do I go about making it a Json5?

**Comment by RogueLogix** [comment]
the same way you made it toml, or just not changing the default file name

**Comment by TheKraken1134** [comment]
thing is idk how I made it toml it just started doing that but Ill change its file name and hopefully that'll work
