### ISSUE TITLE
Bigger Reactor timeouts server on max size 128x128x192

### ISSUE THREAD

**Issue by torbenprobst** [RogueLogix/BiggerSeries#74]
# Problem:
A friend of mine built a Bigger Reactor with the max size of 128x128x192.
As soon as everything were built and placed the server suddenly began to timeout and crash all the time.

Sometimes after 15 mins but often much earlier.

If you need further informations hit me up.

Following parts were used in the max version of the Multiblock Reactor:
- rods
- casing
- control rods
-  controller
-  2x access ports
- powertap

### Crash Log: 
https://mclo.gs/fTIK5l8

### Picture of the Reactor
This is how the reactor looks like:
![image](https://user-images.githubusercontent.com/46575728/200776723-756160db-6282-47a1-8188-8047d71212e5.png)

**Comment by torbenprobst** [comment]
moved to BiggerReactors Repo

**Comment by RogueLogix** [comment]
BiggerSeries/BiggerReactors#66
