### ISSUE TITLE
Wiki not working?

### ISSUE THREAD

**Issue by Pizzy23** [RogueLogix/BiggerSeries#76]
![image](https://user-images.githubusercontent.com/79873070/202730708-b25a071d-dbdf-4052-864b-b5e15b082178.png)

Every time I try to enter the page I get an error.
https://biggerseries.net/

**Comment by Mitchell5200** [comment]
known issue, it's being worked on, https://github.com/BiggerSeries/Wiki/issues/3

**Comment by Pizzy23** [comment]
okay thanks <3
