### ISSUE TITLE
[1.19.2] Reactor fuel, waste, and Rf contents not saving

### ISSUE THREAD

**Issue by ex1le358** [RogueLogix/BiggerSeries#78]
Running on ATM 8 version 1.0.6b modpack, which uses the mod version 0.6.0-beta.6.jar.  I noticed that when I relaunch my single player world, the contents of the reactor disappear.  There would previously have been fuel, waste, and stored Rf present, but when I launch the world again, it's completely empty.  I tried it out formally and surely enough, the contents would never save, although there was only 1 occasion that the contents saved, which was only if I placed 1 ingot in a reactor with NO Rf stored.  Sort of a shot in the dark because I'm not a programmer of any sort, but it seems like when I "save and quit", the only thing that actually saves is the positions of the blocks and not the data corresponding to fuel, waste, and Rf.  I feel like someone would have already come across this issue with this version of the mod, but I couldn't find any.  Maybe it's just the modpack.  Thanks in advance!

Edit: A few points I thought I should add:

-The test is run such that I stop the reactor **before** relaunching the single-player world to give me a more static situation to make an attempt to analyze.
- When I unload the chunk and reload it, the contents are still there
- The reactor intersects a chunk border
- I did the same tests again on the updated version of the modpack (ATM8 1.0.7) and it works now, nothing gets lost from the reactor.  Probably some mod interaction among the multitude that were updated.  I guess we can consider this one closed, but I'll leave it up here just in case someone comes across the same issue as I did.

**Comment by RogueLogix** [comment]
Phosphophyllite (my library, has the multiblock system) update, didn't need to change anything in BiR.
There were multiple different bugs the one change i made introduced, and it took a few versions for me to get them all squashed
<https://github.com/BiggerSeries/Phosphophyllite/blob/0.6.0-beta.6.4/changelog.md>

I'm going to leave this here for visibility, even though the Phos repo would technically be correct.
