### ISSUE TITLE
Needs quartz and philosophyte in this version but still not working

### ISSUE THREAD

**Issue by Enderteck** [RogueLogix/BiggerSeries#82]
How does this makes sense ?

![Screenshot](https://github.com/BiggerSeries/BiggerSeries/assets/123917079/d55a1da8-5e35-4cb5-bb38-adcc4b92c6ec)

**Comment by RogueLogix** [comment]
as Forge/Neo says, lower bound is inclusive upper bound is exclusive, you need an older version of quartz/phos.

**Comment by Enderteck** [comment]
Ok thx
